多语句 : 语句
      | 多语句 分隔符 语句
语句 : 发问未知值
    | 叙述已知值
    | 叙述关系
    | 无误
发问未知值 : 量 "是" 未知数值
叙述已知值 : 量 "是" 数值
叙述关系 : 量 "是" 算式
算式 : 量 四则运算
四则运算 : 运算符 数值
        | 四则运算 运算符 数值
运算符 : "加" | "乘" | "减" | "除以"
未知反馈 : "不知" 发问未知值
未知数值 : "多少"
量 : "摄氏度" | "华氏度"
数值 : 【自然数】
无误 : "没错"
分隔符 : 逗号